### ISSUE TITLE
Add links in a cell

### ISSUE THREAD

**Issue by quentinjolliet** [renrizzolo/contentful-json-table#1]
Hi,

Loving your extension thanks ! However i'd like to add some links on a text added in a cell.
Can you help me on this ? 

Thanks

**Comment by renrizzolo** [comment]
Thanks!

There isn't a direct solution for this, I write html directly into the text, and parse it on the frontend (in my case with  react's `dangerouslySetInnerHTML`.  You could do the same with markdown if you use that.

I'm sure it's possible to make each cell a rich text editor, but seems like overkill.

**Comment by quentinjolliet** [comment]
Thanks for your quick answer !
